### ISSUE TITLE
Терминал Windows по умолчанию работает не в Unicode и не может выводить сообщения на русском

### ISSUE THREAD

**Issue by akalinin-ms** [locumru/locum#1]
Проблемы с кириллицей. Как исправить?

User@**\* /d/**\* (master)
$ locum cap
   identical  Capfile
   identical  config/deploy.rb
   identical  config/deploy/locum.rb
c:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/lib/locum/cli.rb:13:in `add': incompatible character encodings: UTF-8 and IBM866 (Encoding::CompatibilityError)
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in`block in subcommand'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/lib/locum/cap.rb:38:in `ssh_key'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/lib/locum/cli.rb:90:in`cap'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/bin/locum:11:in `<top (required)>'
        from c:/Ruby21/bin/locum:23:in`load'
        from c:/Ruby21/bin/locum:23:in `<main>'

User@*****\* (master)

**Comment by vs-adm** [comment]
Интересно. Какая операционная система и кодировка терминала?

**Comment by akalinin-ms** [comment]
Я все делаю на Windows.
Пробовал и в cmd и в bash.
 По ходу распространенная проблема: https://github.com/Compass/compass/issues/1825

**Comment by vs-adm** [comment]
```
chcp 65001
```

Перед запуском команды не помогает?

**Comment by akalinin-ms** [comment]
нет

***\ThinkServer>chcp
Текущая кодовая страница : 1251

***\ThinkServer>chcp 65001
Active code page: 65001

***\ThinkServer>locum cap
   identical  Capfile
   identical  config/deploy.rb
   identical  config/deploy/locum.rb
C:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/lib/locum/cli.rb:13:in `add': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

**Comment by vs-adm** [comment]
А если выставить еще и `LANG`?

```
set LANG=ru_RU.UTF-8
```

Каким-то образом нужно переключить терминал на Unicode кодировку.
Если ничего не поможет, сделаю переключение языков в gem, с английским такой проблемы скорее всего не будет.

**Comment by akalinin-ms** [comment]
*\ThinkServer>set LANG=ru_RU.UTF-8

*\ThinkServer>locum cap
   identical  Capfile
   identical  config/deploy.rb
   identical  config/deploy/locum.rb
C:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/lib/locum/cli.rb:13:in `add': incompatible

**Comment by akalinin-ms** [comment]
Только теперь он пишет /cli.rb:13:in `add': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

**Comment by vs-adm** [comment]
А кодовая страница терминала выставлена в `65001`?

**Comment by akalinin-ms** [comment]
Да

*\ThinkServer>set LANG=ru_RU.UTF-8

*\ThinkServer>chcp 65001
Active code page: 65001

*\ThinkServer>set LANG=ru_RU.UTF-8

*\ThinkServer>chcp
Active code page: 65001

*\ThinkServer>locum cap
   identical  Capfile
   identical  config/deploy.rb
   identical  config/deploy/locum.rb
C:/Ruby21/lib/ruby/gems/2.1.0/gems/locum-0.1.3/lib/locum/cli.rb:13:in `add': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

**Comment by vs-adm** [comment]
На Stackoverflow советуют использовать Powershell не ниже второй версии, а с обычным cmd.exe, пишут, нормальный Unicode не получить. Или ждать, когда появится возможность настраивать перевод.

Так или иначе файл конфига для `cap` создался, а вот ключик SSH надо загрузить вручную.

**Comment by akalinin-ms** [comment]
Ага. Попробую. Спасибо большое. Тут говорят, что windows "г-но" все. Начинаю верить). Буду смотреть в сторону linux потихоньку.

**Comment by vs-adm** [comment]
Политкорректность мешает мне это сказать, у меня был опыт разработки на Ruby под винду несколько лет назад, переехать в виртуалку на Linux оказалось значительно проще, чем настроить окружение так, чтобы оно работало.

**Comment by akalinin-ms** [comment]
Терминал povershell 2.0 - более недоступен ни где с сайта microsoft, как я понял из за остановки поддержки операционных систем на которых он был доступен. А 1.0 - конечно же выдает ту же ошибку. Не в курсе есть ли какие-либо еще оболочки для Win? В крайнем случае сам скриптом на первое время переведу кириллицу в транслит.

**Comment by vs-adm** [comment]
[Вот здесь](https://www.microsoft.com/en-us/download/details.aspx?id=34595) не то, что нужно?

**Comment by akalinin-ms** [comment]
PS C:\Users\Пользователь> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

---

5      0      10586  117

Все таки версия была обновлена еще вчера. Но ошибка та же. Прежние манипуляции с кодировкой так же не помогли.

**Comment by vs-adm** [comment]
Не совсем понятно, что имеется в виду под "версией". Нужно запустить powershell (не cmd.exe) и попробовать в нём выставить кодировку.

**Comment by akalinin-ms** [comment]
Версия - это версия powershell. Далее все было сделано именно так как вы описываете. PS не справился.
